import unittest

class TestExceptions(unittest.TestCase):
    pass